export const ROOT_URL = "http://localhost:8080";
// export const ROOT_URL = "http://35.175.226.76:8080";
export const LOGO = "https://fontmeme.com/permalink/181215/434dc4936cf31f05fe009a6a3d191b92.png";
export const SIGN_IN_LOGO = "https://fontmeme.com/permalink/181209/d616c788fe2b61f1f05c8f0ddcef6c89.png";
export const apiHeader = {
  withCredentials: true
};

export const USER = {
  SIGN_IN_SUCCESS : "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAILURE",
  SIGN_IN: "SIGN_IN",
  SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
  SIGNUP_FAIL : "SIGNUP_FAIL",
  SIGN_UP: "SIGN_UP",
  SIGN_OUT : "SIGN_OUT",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAIL: "SIGN_OUT_FAIL",
  GET_CUURENT_USER: "GET_CUURENT_USER",
  GET_CUURENT_USER_SUCCESS : "GET_CUURENT_USER_SUCCESS",
  GET_USER_PAID_MOVIES : "GET_USER_PAID_MOVIES",
  GET_USER_PAID_MOVIES_SUCCESS : "GET_USER_PAID_MOVIES_SUCCESS",
  GET_USER_PAID_MOVIES_FAILURE : "GET_USER_PAID_MOVIES_FAILURE",
  GET_USER_SUBSCRIPTION: "GET_USER_SUBSCRIPTION",
  GET_USER_SUBSCRIPTION_SUCCESS: "GET_USER_SUBSCRIPTION_SUCCESS",
  GET_USER_SUBSCRIPTION_FAILURE: "GET_USER_SUBSCRIPTION_FAILURE",
  SET_USER_WATCH_LOG: "SET_USER_WATCH_LOG",
  SET_USER_WATCH_LOG_SUCCESS : "SET_USER_WATCH_LOG_SUCCESS",
  SET_USER_WATCH_LOG_FAIL: "SET_USER_WATCH_LOG_FAIL"
};

export const MOVIE = {
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAIL: 'GET_MOVIES_FAIL',
  UPDATE_FILTERED_MOVIES: 'UPDATE_FILTERED_MOVIES',
  DELETE_MOVIE: "DELETE_MOVIE",
  DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
  DELETE_MOVIE_FAIL: "DELETE_MOVIE_FAIL",
  ADD_MOVIE: "ADD_MOVIE",
  ADD_MOVIE_SUCCESS: "ADD_MOVIE_SUCCESS",
  ADD_MOVIE_FAIL: "ADD_MOVIE_FAIL",
  EDIT_MOVIE:"EDIT_MOVIE",
  EDIT_MOVIE_SUCCESS:"EDIT_MOVIE_SUCCESS",
  EDIT_MOVIE_FAIL: "EDIT_MOVIE_FAIL",
  OPEN_MOVIE_MODAL: "OPEN_MOVIE_MODAL",
  CLOSE_MOVIE_MODAL: "CLOSE_MOVIE_MODAL",
  MOVIE_DETAILS: "MOVIE_DETAILS",
  MOVIE_DETAILS_FAIL: "MOVIE_DETAILS_FAIL",
  MOVIE_DETAILS_SUCCESS: "MOVIE_DETAILS_SUCCESS",
  GET_MOVIE_REVIEWS: "GET_MOVIE_REVIEWS",
  GET_MOVIE_REVIEWS_SUCCESS: "GET_MOVIE_REVIEWS_SUCCESS",
  GET_MOVIE_REVIEWS_FAIL: "GET_MOVIE_REVIEWS_FAIL",
  GET_USER_WATCH_HISTORY: "GET_USER_WATCH_HISTORY",
  GET_USER_WATCH_HISTORY_SUCCESS: "GET_USER_WATCH_HISTORY_SUCCESS",
  GET_USER_WATCH_HISTORY_FAIL: "GET_USER_WATCH_HISTORY_FAIL",
  GET_SEARCH_RESULTS: "GET_SEARCH_RESULTS",
  GET_SEARCH_RESULTS_SUCCESS: "GET_SEARCH_RESULTS_SUCCESS",
  GET_SEARCH_RESULTS_FAIL: "GET_SEARCH_RESULTS_FAIL"
};

export const PAYMENT = {
  PAY_FOR_MOVIE : "PAY_FOR_MOVIE",
  PAY_FOR_MOVIE_SUCCESS : "PAY_FOR_MOVIE_SUCCESS",
  PAY_FOR_MOVIE_FAIL : "PAY_FOR_MOVIE_FAIL",
  PAY_USER_SUBSCRIPTION: "PAY_USER_SUBSCRIPTION",
  PAY_USER_SUBSCRIPTION_SUCCESS: "PAY_USER_SUBSCRIPTION_SUCCESS",
  PAY_USER_SUBSCRIPTION_FAILURE: "PAY_USER_SUBSCRIPTION_FAILURE"
};
