export const ROOT_URL = "http://localhost:8080";

export const LOGO = "https://fontmeme.com/permalink/181209/d616c788fe2b61f1f05c8f0ddcef6c89.png";
export const SIGN_IN_LOGO = "https://fontmeme.com/permalink/181209/d616c788fe2b61f1f05c8f0ddcef6c89.png";
export const apiHeader = {
  withCredentials: true
};

export const USER = {
  SIGN_IN_SUCCESS : "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAILURE",
  SIGN_IN: "SIGN_IN",
  SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
  SIGNUP_FAIL : "SIGNUP_FAIL",
  SIGN_UP: "SIGN_UP",
  SIGN_OUT : "SIGN_OUT",
}

export const MOVIE = {
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAIL: 'GET_MOVIES_FAIL',
  DELETE_MOVIE: "DELETE_MOVIE",
  DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
  DELETE_MOVIE_FAIL: "DELETE_MOVIE_FAIL",
  ADD_MOVIE: "ADD_MOVIE",
  ADD_MOVIE_SUCCESS: "ADD_MOVIE_SUCCESS",
  ADD_MOVIE_FAIL: "ADD_MOVIE_FAIL",
  EDIT_MOVIE:"EDIT_MOVIE",
  EDIT_MOVIE_SUCCESS:"EDIT_MOVIE_SUCCESS",
  EDIT_MOVIE_FAIL: "EDIT_MOVIE_FAIL",
  OPEN_MOVIE_MODAL: "OPEN_MOVIE_MODAL",
  CLOSE_MOVIE_MODAL: "CLOSE_MOVIE_MODAL",
};

